# 1.python基础试题

1.1 python 中boolean、float 和 int 分别表示什么？

In [6]:
print("boolean代表True/False这类逻辑变量")
print("float代表如3.14这类浮点数")
print("int代表如3这类整数")

boolean代表True/False这类逻辑变量
float代表如3.14这类浮点数
int代表如3这类整数


1.2  设计求1-2+3-4+5 ... 99的所有数的和

In [2]:
sum(range(1,100,2))-sum(range(2,99,2))

50

1.3  将字符串 s="yoyo" 转换成列表

In [3]:
list("yoyo")

['y', 'o', 'y', 'o']

# 2. python进阶基础试题

2.1     for i in range(1,100)[2::3][-10:]: 

                print i 
                
        理解这段代码，并说出它是如何取数的

In [13]:
print("从1到100中，从3开始每隔3取一个数，直到99，然后取结果最后10个数字，就是72,75,78,81,84,87,90,93,96,99")

从1到100中，从3开始每隔3取一个数，直到99，然后取结果最后10个数字，就是72,75,78,81,84,87,90,93,96,99


2.2 使用init 实例化时自动运行  分别计算单只股票最高价和收盘价两个时间点差值问题,可统一为one、two两个时间点,其最高价和收盘价赋值为 one(15,7) two(66,20)

In [20]:
class Stock:
    def __init__(self,one,two):
        self.one_dif = {'one_dif': one[0]-one[1]}
        self.two_dif = {'two_dif': two[0]-two[1]}
        print(self.one_dif)
        print(self.two_dif)
        pass
stock = Stock((15,7),(66,20))

{'one_dif': 8}
{'two_dif': 46}


# 3. pandas数据处理试题

3.1 如何查看列名、怎么对数据转置

In [26]:
# 查看列名例子
import pandas as pd
df = pd.DataFrame([[1,2],[3,4]],columns=['a','b'])
print(df.columns)
# 对数据转置例子
print(df.T)

Index(['a', 'b'], dtype='object')
   0  1
a  1  3
b  2  4


3.2 读取data里的600029这只股票的DataFrame,将其收盘价转换成用Numpy的Array格式，并用talib计算10日EMA值，返回ndarray的最后五个值

In [61]:
import pandas as pd
sheetnames = pd.ExcelFile('sz50.xlsx',on_demand = True).sheet_names
from datetime import datetime
data = {}
for s in sheetnames:
    data[s] = pd.read_excel('sz50.xlsx',sheet_name=s, index_col='datetime')

In [29]:
df = data['600029.XSHG']
import numpy as np
import talib as ta
close = np.array(df['close'])
print(ta.EMA(close, 10)[-5:])

[15.08227205 15.2564044  15.44433088 15.72172526 15.96322976]


3.3 读取sz50.xlsx的['600029.XSHG','600050.XSHG','601318.XSHG']的全数据做成Panel

In [40]:
stocks = ['600029.XSHG','600050.XSHG','601318.XSHG']
stocks_dict = {}
for stock in stocks:
    stocks_dict[stock] = data[stock]
stocks_pn = pd.Panel(stocks_dict)
print(stocks_pn)

<class 'pandas.core.panel.Panel'>
Dimensions: 3 (items) x 215 (major_axis) x 5 (minor_axis)
Items axis: 600029.XSHG to 601318.XSHG
Major_axis axis: 2017-01-03 15:00:00 to 2017-11-20 15:00:00
Minor_axis axis: close to volume


C:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2963: FutureWarning: 
Panel is deprecated and will be removed in a future version.
The recommended way to represent these types of 3-dimensional data are with a MultiIndex on a DataFrame, via the Panel.to_frame() method
Alternatively, you can use the xarray package http://xarray.pydata.org/en/stable/.
Pandas provides a `.to_xarray()` method to help automate this conversion.

  exec(code_obj, self.user_global_ns, self.user_ns)


3.4把Panel转成ndim为3的Numpy，然后用array的切片读取ndim为2的三只股票最近20天的收盘价

In [58]:
M = np.array(stocks_pn)
print(M.shape)
print(M[:,-20:,0])

(3, 215, 5)
[[ 13.85  13.82  13.83  14.11  14.25  14.39  15.1   15.15  15.22  14.97
   14.89  14.99  14.71  15.07  15.35  16.    16.04  16.29  16.97  17.05]
 [  8.53   8.56   8.62   8.88   9.25   9.24   9.43   9.25   9.02   9.15
    9.63   9.5    9.9    9.97   9.96   9.49   9.68   9.61   9.63   9.8 ]
 [134.83 134.56 137.5  143.18 143.48 144.15 143.61 143.65 144.35 143.36
  146.41 144.71 148.56 156.53 157.12 157.72 154.99 163.52 168.58 169.57]]


3.5 建立一个5*5的矩阵，值从0到24

In [60]:
print(np.array(range(25)).reshape(5,5))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
